name: main

on: [push]

env:
  FOO: bar

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: linux
          arch: amd64
          runner: ubuntu-24.04
          extension: 'bin'
        - target: win
          arch: amd64
          runner: ubuntu-24.04
          extension: 'exe'
        - target: linux
          arch: arm64
          runner: ubuntu-24.04-arm
          extension: 'bin'
        - target: macos
          arch: arm64
          runner: macos-26
          extension: 'app'

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - name: install required packages
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libwayland-dev libxkbcommon-dev tree
        shell: bash
        if: ${{ startsWith(matrix.runner, 'ubuntu') }}
      - name: install cross-compilation packages
        run: sudo apt-get install -y gcc-mingw-w64-x86-64
        shell: bash
        if: ${{ startsWith(matrix.runner, 'ubuntu') && matrix.target == 'win' }}
      - name: set executable name
        run: |
          exec_name=stingray-${{ matrix.target }}-${{matrix.arch}}.${{matrix.extension}}
          echo "EXEC_NAME=${exec_name}" >> $GITHUB_ENV

      - name: check executable name
        run: echo "${{env.EXEC_NAME}}"

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.11'
      - name: Install dependencies
        run: go get .
      - name: install tool deps
        run: make install
      - name: run tests
        run: make test
      - name: Build
        run: go build -v -o "${{ env.EXEC_NAME }}"
        if: ${{ matrix.target != 'win' }}

      # CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -ldflags "-s -w"
      - name: Build windows executable
        run: go build -v -ldflags "-s -w" -o "${{ env.EXEC_NAME }}"
        env:
          CGO_ENABLED: 1
          CC: x86_64-w64-mingw32-gcc
          GOOS: windows
          GOARCH: amd64
        if: ${{ matrix.target != 'win' }}
      - name: run checks
        run: make check
        if: ${{ matrix.target != 'win' }}
      - name: archive the executable
        run: tar -cvf ${{env.EXEC_NAME}}.tar ${{ env.EXEC_NAME }}

      - name: see what we have in working dir
        run: tree
        shell: bash
        if: ${{ matrix.os ==  'linux' }}

      - name: Upload archived executable
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.EXEC_NAME }}.tar
          path: ${{github.workspace}}/${{ env.EXEC_NAME }}.tar
          if-no-files-found: error
          archive: false
